title: Integrated editor project test
hero_image: images/banner.png
description: a test to create an editor project
version: 1
listed: false
copyedit: false
last_tested: "2025-01-01"
steps:
  - title: First step title
  - title: Second step title

